# API Keys (will be overridden by environment variables if not set)
groq_api_key: ""
openai_api_key: ""

# Available LLM models
llm_models:
  - llama3-8b-8192
  - mixtral-8x7b-32768
  - gemma-7b-it
  - gemma2-9b-it
  - llama-3.1-8b-instant

# Default model
default_model: "mixtral-8x7b-32768"

# Model Parameters
temperature: 0.7
max_tokens: 1000

# File Paths
data_dir: "data"
vector_db_path: "vector_db"

# Chunk Size for Text Splitting
chunk_size: 1000
chunk_overlap: 200